services:

  api:
    image: ${DOCKER_REGISTRY-}disasterallocationresourceapi
    build:
      context: .
      dockerfile: DisasterAlloctionResource.Api/Dockerfile
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    container_name: override_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5