services:

  api:
    image: ${DOCKER_REGISTRY-}disasterallocationresourceapi
    build:
      context: .
      dockerfile: DisasterAllocationResource.Api/Dockerfile
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    container_name: override_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379 